# ==============================================================================
# Splunk Data Ingestion Configuration File
# Place inside: /opt/splunk/etc/apps/<your_app_name>/local/inputs.conf
# ==============================================================================

[udp://1514]
connection_host = ip
index = main
sourcetype = pfsense
no_appending_timestamp = true
description = Inbound UDP Syslog listener for pfSense perimeter firewall telemetry
