# ==============================================================================
# Splunk Search-Time Field Extraction Configuration File
# Place inside: /opt/splunk/etc/apps/<your_app_name>/local/props.conf
# ==============================================================================

[pfsense]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
category = Network & Security
description = Forces line-by-line streaming optimizations for pfSense raw payload streams
